### ISSUE TITLE
Permission for Copying the Content

### ISSUE THREAD

**Issue by philsalti** [wesbos/dad-jokes#287] opened 2024-02-03 13:11 UTC
Hi wesbos
I have been running a jokes related website to make people laugh and happy. I just wanna ask you can I copy your jokes and post them on my [funnpedia](https://funnpedia.com/) blog? I will be very happy if you allow me and very thankful to you. Thanks in Advance!

**Comment by styfle** [comment] 2024-02-03 13:15
- Related to #261

**Comment by styfle** [comment] 2024-12-09 00:54
Closing since the domain is no longer registered and this is basically a duplicate of the other issue

<img width="530" alt="image" src="https://github.com/user-attachments/assets/3b5c2a53-c053-4295-81fc-4a1c4aba9d82">

**Closed by styfle** 2024-12-09 00:54 UTC
